global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:4000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # User Service
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:4001']
    metrics_path: '/api/users/metrics'
    scrape_interval: 30s

  # Course Service
  - job_name: 'course-service'
    static_configs:
      - targets: ['course-service:4002']
    metrics_path: '/api/courses/metrics'
    scrape_interval: 30s

  # Content Service
  - job_name: 'content-service'
    static_configs:
      - targets: ['content-service:4003']
    metrics_path: '/api/content/metrics'
    scrape_interval: 30s

  # Progress Service
  - job_name: 'progress-service'
    static_configs:
      - targets: ['progress-service:4004']
    metrics_path: '/api/progress/metrics'
    scrape_interval: 30s

  # Search Service
  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:4010']
    metrics_path: '/api/search/metrics'
    scrape_interval: 30s

  # Infrastructure
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']

  - job_name: 'consul'
    static_configs:
      - targets: ['consul:8500']

  # Node Exporter (if deployed)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # cAdvisor (if deployed)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']